baseURL: 'https://blog.laurencejones.dev'
languageCode: 'en'
title: 'DevSecOps'
theme: PaperMod
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  env: ${VAR:.Hugo.Environment} # to enable google analytics, opengraph, twitter-cards and schema.
  title: DevSecOps
  description: "DevSecOps"
  keywords: [Blog, Security, OSINT, Cyber Security, PaperMod]
  author: Loz
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  ShowCodeCopyButtons: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
    msapplication_TileColor: "#603cba"
    theme_color: "#ffffff"
  label:
    text: "DevSecOps"
    icon: /me.png
    iconHeight: 55

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: DevSecOps

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ImportModule"
    - name: github
      url: "https://github.com/laurencejjones"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
